# Generated by Django 5.0.7 on 2024-07-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Mobile', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.BigIntegerField()),
            ],
        ),
    ]
