# Generated by Django 5.0.7 on 2024-07-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.BigIntegerField()),
                ('Doctor', models.CharField(max_length=25)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Detail', models.TextField()),
            ],
        ),
    ]
