# Generated by Django 5.0.7 on 2024-08-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_contact_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.BigIntegerField()),
            ],
        ),
    ]
